apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: sa
data:
  PORT: "50055"
  DB_HOST_PAYMENT: "payment-db-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME_PAYMENT: "payment_db"
  RABBITMQ_URL: "amqp://admin:123456@rabbitmq-service:5672"
  ORDER_SERVICE_URL: "order-service:50053"
