apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: sa
  labels:
    app: auth-service
spec:
  replicas: 2 # Ponemos 2 para tener alta disponibilidad en el cluster
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-container
          # RECUERDA: Cambia 'tu-usuario-docker' por tu usuario real de Docker Hub
          image: pampam4188/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            # --- Variables desde el ConfigMap ---
            - name: DB_HOST_AUTH
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: DB_HOST_AUTH
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: DB_USER
            - name: DB_NAME_AUTH
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: DB_NAME_AUTH
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: PORT

            # --- Variables desde el Secret ---
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: sa
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 50051 # Puerto por el que otros servicios buscarán al Auth
      targetPort: 50051 # Puerto real del contenedor
  type: ClusterIP # Uso interno dentro del cluster (ideal para gRPC)
