apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: sa
data:
  # Base de Datos
  DB_HOST_AUTH: "auth-db-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME_AUTH: "auth_db"
  # Aplicación
  PORT: "50051"
