apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-service-config
  namespace: sa
data:
  PORT: "50052"
  DB_HOST_REST: "restaurant-db-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME_REST: "restaurant_db"
  RABBITMQ_URL: "amqp://admin:123456@rabbitmq-service:5672"
