apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-db-pvc
  namespace: sa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-db
  namespace: sa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-db
  template:
    metadata:
      labels:
        app: restaurant-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "restaurant_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-service-secrets
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: restaurant-db-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: restaurant-db-storage
          persistentVolumeClaim:
            claimName: restaurant-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-db-service
  namespace: sa
spec:
  selector:
    app: restaurant-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
