version: "3.8"

services:
  # --- MICROSERVICIOS ---

  auth-db:
    image: postgres:latest
    container_name: auth_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/auth-postgres:/var/lib/postgresql
    networks:
      - delivereats-network

  restaurant-db:
    image: postgres:latest
    container_name: restaurant_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: restaurant_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/restaurant-postgres:/var/lib/postgresql
    networks:
      - delivereats-network

  order-db:
    image: postgres:latest
    container_name: order_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - ./data/order-postgres:/var/lib/postgresql
    networks:
      - delivereats-network

  delivery-db:
    image: postgres:latest
    container_name: delivery_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: delivery_db
    ports:
      - "5435:5432"
    volumes:
      - ./data/delivery-postgres:/var/lib/postgresql
    networks:
      - delivereats-network

  payment-db:
    image: postgres:latest
    container_name: payment_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: payment_db
    ports:
      - "5436:5432"
    volumes:
      - ./data/payment-postgres:/var/lib/postgresql
    networks:
      - delivereats-network

  fx-db:
    image: redis:alpine
    container_name: fx_db_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - delivereats-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto para que los microservicios se conecten
      - "15672:15672" # Puerto para ver el Dashboard en el navegador
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - delivereats-network

networks:
  delivereats-network:
    driver: bridge
