name: Payment Service - DeliverEats

on:
  push:
    branches: [main]
    paths:
      - "delivereats/payment-service/**" # Solo se activa si hay cambios en el servicio de Auth

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Setup de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "delivereats/payment-service/package-lock.json"

      - name: 3. Instalar dependencias
        run: |
          cd delivereats/payment-service
          npm ci

      - name: 4. Ejecutar Tests Unitarios (Falla si < 70% cobertura)
        run: |
          cd delivereats/payment-service
          npm run test:cov

      # --- AQUÍ EMPIEZA EL CD (ENTREGA CONTINUA) ---

      - name: 5. Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 6. Build y Push de imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: ./delivereats/payment-service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:${{ github.sha }}

      # --- PASO A KUBERNETES ---

      - name: 7. Autenticación en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 8. Obtener credenciales del clúster GKE
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 9. Desplegar manifiestos en Kubernetes
        run: |
          # Actualizamos la imagen en el deployment
          sed -i "s|image: .*payment-service:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:${{ github.sha }}|g" k8s/payment/payment-deployment.yaml

          # Aplicar en orden correcto
          kubectl apply -f k8s/payment/payment-configmap.yaml
          kubectl apply -f k8s/payment/payment-secret.yaml
          kubectl apply -f k8s/payment/payment-db.yaml
          kubectl apply -f k8s/payment/payment-deployment.yaml
